apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /wordpress
    server: 172.31.62.186
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
